[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    https://github.com/sparkfun/SparkFun_VL53L5CX_Arduino_Library.git#v1.0.3
